import type { Metadata } from 'next';
import { responsive } from '@/lib/images';
import { pageMetadata,jsonLd,siteOrigin } from '@/lib/seo';
import Link from '@/components/site-link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { getPublishedContent } from '@/lib/published-content';
import { projectAccess } from '@/lib/project-access';
type Props={params:Promise<{slug:string}>};
export const dynamicParams=false;
// Live client sites have no page of their own: their cards open the site, and old links redirect there (next.config.ts).
export async function generateStaticParams(){const {projects}=await getPublishedContent();return projects.filter(p=>projectAccess(p)!=='visit').map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {projects}=await getPublishedContent();const {slug}=await params;const p=projects.find(p=>p.slug===slug);return pageMetadata('/projects/'+slug,p?.title||'Project not found',p?.description||'Project by Rushan Haque.');}
export default async function ProjectDetail({params}:Props){const {projects}=await getPublishedContent();const {slug}=await params;const project=projects.find(p=>p.slug===slug);if(!project||projectAccess(project)==='visit')notFound();const access=projectAccess(project);const pages=projects.filter(p=>projectAccess(p)!=='visit');const next=pages[(pages.indexOf(project)+1)%pages.length];return <main id="main-content" className="project-detail"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({"@context":"https://schema.org","@type":"CreativeWork",name:project.title,description:project.description,...(project.details?{abstract:project.details.does[0],keywords:project.details.stack.join(", ")}:{}),url:siteOrigin+"/projects/"+slug,creator:{"@type":"Person",name:"Rushan Haque"}})}}/><div className="container detail-head"><Link href="/projects" className="back-link"><ArrowLeft size={15}/>All projects</Link><div className="detail-title"><div><span className="eyebrow">PROJECT {project.number} / {project.category}</span><h1 suppressHydrationWarning data-reveal>{project.title}</h1></div><span className="status-pill"><span/>{project.status}</span></div><div className="detail-meta"><div><span>DISCIPLINE</span><strong>{project.category==='Client work'?'Web design & development':project.discipline}</strong></div><div><span>YEAR</span><strong>{project.year}</strong></div><div><span>CONTEXT</span><strong>{project.category}</strong></div>{access==='visit'&&<a href={project.url} target="_blank" rel="noopener noreferrer" className="button primary">Visit site <ArrowUpRight size={17}/></a>}{access==='request'&&<Link href={`/connect?project=${encodeURIComponent(project.title)}&message=${encodeURIComponent('Hi Rushan, I would like access to '+project.title+'.')}`} className="button primary">Request access <ArrowUpRight size={17}/></Link>}{access==='soon'&&<span className="status-pill"><span/>Coming soon</span>}</div></div>{project.image?<div className="detail-image container" data-reveal><img className={project.imageBlurred?'unreleased-preview':undefined} src={project.image} {...responsive(project.image,'(max-width: 1500px) 100vw, 1440px')} alt={`${project.title} project website`} width="1600" height="780" fetchPriority="high"/></div>:<div className="detail-type-art container" aria-hidden="true"><span>{project.number} / {project.discipline}</span><strong>{project.title}<em><ArrowUpRight size="0.7em" strokeWidth={1.25}/></em></strong><span>{project.year}</span></div>}<section className="container detail-overview"><span className="eyebrow">THE PROJECT</span><div><h2 suppressHydrationWarning>{project.status==='Coming soon'?'Coming soon.':project.category==='Client work'?'Built for a client.':'A personal experiment.'}</h2><p>{project.description}</p><div className="tag-list">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div></section>{project.details&&<section className="container project-how" aria-label="How it works">
<div className="project-how-head"><span className="eyebrow">WHAT IT DOES</span><div className="project-how-does">{project.details.does.map((t,i)=><p key={i}>{t}</p>)}</div></div>
<div className="project-how-steps"><span className="eyebrow">HOW IT WORKS</span><ol>{project.details.steps.map((st,i)=><li key={st.title}><span>{String(i+1).padStart(2,'0')}</span><h3>{st.title}</h3><p>{st.text}</p></li>)}</ol></div>
<div className="project-how-foot">{project.details.stack.length>0&&<div><span className="eyebrow">BUILT WITH</span><div className="tag-list">{project.details.stack.map(t=><span key={t}>{t}</span>)}</div></div>}{project.details.note&&<div className="project-how-note"><span className="eyebrow">GOOD TO KNOW</span><p>{project.details.note}</p></div>}</div>
</section>}{project.caseStudy&&<section className="container case-narrative"><span className="eyebrow">THE THINKING</span><h2 suppressHydrationWarning>How it <em>was made.</em></h2><p>{project.caseStudy.context}</p><dl><dt>Contribution</dt><dd>{project.caseStudy.role}</dd></dl><div className="case-decisions">{project.caseStudy.decisions.map((d,i)=><article key={d.title}><span>0{i+1}</span><h3>{d.title}</h3><p>{d.text}</p></article>)}</div><details><summary>Notes</summary><p>{project.caseStudy.reflection}</p></details></section>}<section className="container detail-conversation"><h2 suppressHydrationWarning>Something similar <em>in mind?</em></h2><Link href={`/connect?project=${encodeURIComponent(project.title)}`} className="button primary">Contact <ArrowUpRight size={17}/></Link></section><Link className="next-project container" href={`/projects/${next.slug}`}><span className="eyebrow">NEXT</span><span>{next.title}<ArrowUpRight/></span></Link></main>;}
