import { pageMetadata } from '@/lib/seo';
import Link from '@/components/site-link';
import { ArrowUpRight,Clock,Video } from 'lucide-react';
import { setting } from '@/lib/admin';
import { InquiryForm } from '@/components/inquiry-form';
import { bookingUrl } from '@/lib/content';
export const metadata=pageMetadata('/schedule','Schedule a conversation','Request a time to talk with Rushan Haque.');
export const dynamic="force-dynamic";
export default function Schedule(){const configured=setting("CAL_BOOKING_URL")||bookingUrl;let booking="";try{const url=new URL(configured);if(url.protocol==="https:"&&["cal.com","www.cal.com","calendly.com","www.calendly.com"].includes(url.hostname))booking=url.href;}catch{}return <main id="main-content" className="container contact-layout schedule-layout"><div className="contact-intro"><span className="eyebrow">SCHEDULE</span><h1 suppressHydrationWarning data-reveal>Let’s <em>talk.</em></h1><p>Thirty minutes on video. Bring the problem; we’ll work out the rest together.</p><div className="call-details"><span><Clock size={17}/>30 minutes</span><span><Video size={17}/>Video call</span></div><Link href="/connect" className="text-link">Send an enquiry instead <ArrowUpRight size={16}/></Link></div>{booking?<section className="inquiry-form cal-booking"><h2 suppressHydrationWarning>Pick a time.</h2><p className="form-helper">Live availability in your timezone. You’ll get a calendar invite straight away.</p><iframe className="cal-frame" src={`${booking}${booking.includes('?')?'&':'?'}embed=true&theme=light&layout=month_view`} title="Book a call with Rushan Haque" loading="lazy"/><p className="form-helper">Calendar not loading? <a href={booking} target="_blank" rel="noopener noreferrer">Open it in a new tab</a> or <a href="mailto:rushanulhaque@gmail.com">write to me</a>.</p></section>:<InquiryForm kind="call"/>}</main>;}
