import type { Metadata } from 'next';
import { CredentialCatalogue } from '@/components/credential-catalogue';
import { pageMetadata } from '@/lib/seo';
import { notFound } from 'next/navigation';
import { ArrowUpRight } from 'lucide-react';
import { PageIntro } from '@/components/page-intro';
import { email,socials } from '@/lib/content';
const titles:Record<string,string>={certifications:'Certifications & awards',privacy:'Privacy',accessibility:'Accessibility'};
type Props={params:Promise<{page:string}>};
export const dynamicParams=false;
export function generateStaticParams(){return Object.keys(titles).map(page=>({page}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {page}=await params;return pageMetadata('/'+page,titles[page]||'Page not found',`${titles[page]||'Page'} — Rushan Haque.`);}
export default async function InformationPage({params}:Props){const {page}=await params;if(!titles[page])notFound();
  if(page==='certifications')return <main id="main-content"><PageIntro eyebrow="LEARNING / SELECTED CREDENTIALS" title="Always a student" accent="of something." description="Selected certifications and job simulations across software, data, and technology. Part of an ongoing commitment to learn by doing."/><CredentialCatalogue/><p className="container page-note">Job simulations are self-paced learning programmes. They do not imply employment with the organisations named.</p></main>;
  if(page==='privacy')return <main id="main-content"><PageIntro eyebrow="THE SMALL PRINT / PLAIN LANGUAGE" title="Your information," accent="treated thoughtfully." description="This page explains the information collected by this portfolio and how to get in touch about it."/><section className="container policy-body"><h2>When you get in touch</h2><p>Project enquiries, call requests, and reviews collect the details you choose to provide: your name, email, message, and relevant project or scheduling preferences. These are stored so Rushan can review and respond to them.</p><h2>Reviews</h2><p>A review is held for moderation. Your email is kept private. With your permission, your name, company, rating, and review may be published on this portfolio.</p><h2>Storage and site preferences</h2><p>Submissions are stored in the site’s database. Your project-layout preference is saved on your device. The site does not use advertising trackers. The hosting provider may process operational and security information needed to serve the site.</p><h2>Anonymous interaction counts</h2><p>The site counts project opens, contact and scheduling clicks, and form starts by page and day. No visitor identifier, message, email, or query string is sent with these events. Counts are retained for up to 90 days and respect Do Not Track and Global Privacy Control. Received submissions are counted separately in the private inbox.</p><h2>Review moderation</h2><p>Reviews are checked for consent and a genuine project relationship before publication. Spam, abusive content, and unverifiable claims may be rejected; critical feedback is not excluded merely for being negative. You may request correction or removal by email.</p><h2>Call requests</h2><p>A requested time is a preference, not a confirmed appointment. Confirmation is arranged separately by email.</p><h2>Questions or deletion requests</h2><p>Contact <a href={`mailto:${email}`}>{email}</a> to ask about your information or request deletion. Include enough detail to identify your submission.</p><p className="small-note">Updated September 2026.</p></section></main>;
  return <main id="main-content"><PageIntro eyebrow="ACCESSIBILITY / OPEN TO EVERYONE" title="An experience" accent="you can make your own." description="This site is designed to be navigable with a keyboard, comfortable on small screens, and usable with touch or pointer input."/><section className="container policy-body"><h2>A quieter experience</h2><p>Your system’s reduced-motion setting is respected, and the Motion switch in the footer turns animation, pinned scenes, and the custom cursor off on any device. Your choice is remembered. All content remains available.</p><h2>Navigation and reading</h2><p>Use the skip-to-content link, visible keyboard focus, descriptive form labels, and native browser zoom. The horizontal work reel follows keyboard focus, and every project is also listed in the archive.</p><h2>Something getting in the way?</h2><p>Accessibility is an ongoing practice. If a part of this site is difficult to use, email <a href={`mailto:${email}`}>{email}</a> with the page and the issue you encountered.</p><div className="social-links">{socials.slice(0,2).map(s=><a href={s.url} key={s.name} target="_blank" rel="noopener noreferrer">{s.name}<ArrowUpRight size={15}/></a>)}</div></section></main>;
}
