export const dynamic='force-dynamic';
import { ApprovedReviews } from '@/components/approved-reviews';
import type { Metadata } from 'next';
import { CredentialCatalogue } from '@/components/credential-catalogue';
import { pageMetadata, jsonLd, siteOrigin } from '@/lib/seo';
import Link from '@/components/site-link';
import { notFound } from 'next/navigation';
import { ArrowUpRight, Asterisk, MapPin } from 'lucide-react';
import { PageIntro } from '@/components/page-intro';
import { DesignPlayground, ServiceAccordion } from '@/components/interactive';
import { getPublishedContent } from '@/lib/published-content';
import { email,socials } from '@/lib/content';
const titles:Record<string,string>={about:'The person behind the work',services:'What we can make together',experience:'A practice shaped by doing',certifications:'Always learning',collaborations:'A wider circle',reviews:'A few kind words',playground:'The playground',privacy:'Privacy',accessibility:'Accessibility'};
type Props={params:Promise<{page:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {page}=await params;return pageMetadata('/'+page,titles[page]||'Page not found',`Explore ${page} from the independent practice of Rushan Haque.`);}
export default async function InformationPage({params}:Props){const {experience,certifications,reviews}=await getPublishedContent();const {page}=await params;if(!titles[page])notFound();
  if(page==='about')return <main id="main-content"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'ProfilePage',url:siteOrigin+'/about',mainEntity:{'@type':'Person',name:'Rushan Haque',url:siteOrigin+'/about',sameAs:socials.map(s=>s.url)}})}}/><PageIntro eyebrow="THE PERSON / BEHIND THE PIXELS" title="Curious by nature." accent="Intentional by design." description="I’m Rushan. An independent designer, developer, and writer based in Moradabad, India. I like making things that look considered, work beautifully, and have something to say."/><section className="container about-grid"><div className="about-letterform" data-reveal><span>RUSHAN HAQUE / AN OPEN PRACTICE</span><strong>r<em>h.</em></strong><div><MapPin size={15}/>Moradabad, India <span>↗</span></div></div><div className="about-copy" data-reveal><span className="eyebrow">A FEW DIFFERENT WAYS OF SEEING</span><h2>At home between<br/><em>logic and feeling.</em></h2><p>I work across web design, development, and writing. That combination gives me different ways into a problem: how it should work, how it should feel, and how clearly it can be explained.</p><p>My work spans commercial websites, personal tools, AI experiments, and IoT projects. Away from the build, I write about technology and ideas, with another part of my practice rooted in Urdu poetry.</p><p>I’m pursuing a B.Tech in Computer Science with IoT at MIT Moradabad. The learning happens in the classroom, and just as often while making something of my own.</p><div className="tag-list"><span>Design</span><span>Development</span><span>Writing</span><span>Curiosity</span></div><Link className="text-link" href="/experience">The journey so far <ArrowUpRight size={17}/></Link></div></section><section className="container section about-principles"><span className="eyebrow">THINGS I COME BACK TO</span><div className="principle-grid">{[['01','Be interested.','Ask the question behind the question. Good work begins with understanding.'],['02','Care about the details.','The small decisions are the experience. Spacing, words, speed, and the feeling of a click.'],['03','Keep it human.','Technology is a means. A useful, memorable experience is the point.']].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section></main>;
  if(page==='services')return <main id="main-content"><PageIntro eyebrow="SERVICES / MADE AROUND YOU" title="Your next chapter." accent="Made with intention." description="A distinctive website, a useful tool, a clearer story. We start with what you need to achieve and shape the work around it."/><section className="container services-page"><div className="service-note"><Asterisk size={55} strokeWidth={1}/><h2>One thoughtful<br/><em>conversation first.</em></h2><p>No one-size-fits-all package. We’ll agree the scope, timeline, and investment before the work begins.</p><Link href="/contact" className="button primary">Start a conversation <ArrowUpRight size={17}/></Link></div><ServiceAccordion/></section><section className="container section principle-grid">{[['Clarity from day one.','A defined scope, milestones, and space for feedback.'],['Built for real people.','Responsive design, accessibility, and performance are part of the work.'],['Yours to move forward.','A clear handover and an agreed approach to updates after launch.']].map(([t,p])=><article key={t}><h3>{t}</h3><p>{p}</p></article>)}</section></main>;
  if(page==='experience')return <main id="main-content"><PageIntro eyebrow="EXPERIENCE / A CONTINUING STORY" title="A practice shaped" accent="by doing." description="Design, development, writing, and the experience of understanding how businesses work. Each role adds another perspective."/><section className="container timeline">{experience.map((e,i)=><article key={e.role} data-reveal><div className="timeline-date"><span>0{i+1}</span>{e.period}</div><details><summary><div><h2>{e.role}</h2><h3>{e.company}</h3></div></summary><p>{e.description}</p><Link href={e.role.includes("Writer")?"/writing":"/projects"} className="text-link">Explore the practice <ArrowUpRight size={16}/></Link></details></article>)}</section><section className="container section education"><span className="eyebrow">EDUCATION</span><h2>Computer Science.<br/><em>Connected to the world.</em></h2><p>B.Tech · Computer Science with IoT<br/>MIT Moradabad · 2023–2027</p><Link href="/certifications" className="text-link">Beyond the classroom <ArrowUpRight size={17}/></Link></section></main>;
  if(page==='certifications')return <main id="main-content"><PageIntro eyebrow="LEARNING / SELECTED CREDENTIALS" title="Always a student" accent="of something." description="Selected certifications and job simulations across software, data, and technology. Part of an ongoing commitment to learn by doing."/><CredentialCatalogue/><p className="container page-note">Job simulations are self-paced learning programmes. They do not imply employment with the organisations named.</p></main>;
  if(page==='collaborations')return <main id="main-content"><PageIntro eyebrow="COLLABORATIONS / A WIDER CIRCLE" title="Some ideas need" accent="more than one mind." description="For a broader brief, we can explore a collaboration that brings the right skills around the same table."/><section className="container collaboration-grid">{[['01','Digital marketing','Campaign direction and a considered approach to reaching your audience.'],['02','SEO & GEO','Search visibility and content structured to be understood and discovered.'],['03','Cloud & business systems','Exploring the infrastructure, ERP, or CRM needs behind your digital presence.'],['04','Social & video','Content planning, social presence, and video production within an agreed scope.']].map(([n,t,p])=><article data-reveal key={n}><span className="eyebrow">{n} / POSSIBILITIES</span><h2>{t}</h2><p>{p}</p><p className="collaboration-boundary">Partner-supported scope. Delivery lead, specialist responsibilities, fees, and support are agreed in writing before work begins. No named partner is implied.</p><Link href={`/contact?service=${encodeURIComponent(t)}`} className="text-link">Explore a collaboration <ArrowUpRight size={17}/></Link></article>)}</section><section className="container collaboration-note"><h2>Independent creative?<br/><em>There’s room at the table.</em></h2><p>If you care deeply about your craft and think we could make something good together, I’d like to hear from you.</p><a href={`mailto:${email}?subject=Let%E2%80%99s%20collaborate`} className="button primary">Introduce yourself <ArrowUpRight size={17}/></a></section></main>;
  if(page==='reviews')return <main id="main-content"><PageIntro eyebrow="KIND WORDS / SHARED EXPERIENCES" title="The work matters." accent="So do the people." description="A few words from people I’ve worked with, originally shared on my portfolio."/><section className="container review-grid"><ApprovedReviews/>{reviews.map(r=><article className="review-card" data-reveal key={r.name}><blockquote>“{r.quote}”</blockquote><div className="review-person"><span className="review-avatar">{r.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><div><strong>{r.name}</strong><span>{r.company}</span></div></div></article>)}</section><div className="container section"><Link href="/write-a-review" className="button primary">Worked together? Share your experience <ArrowUpRight size={17}/></Link></div></main>;
  if(page==='playground')return <main id="main-content"><PageIntro eyebrow="THE PLAYGROUND / AN INVITATION TO EXPLORE" title="A little curiosity." accent="A lot of possibility." description="Choose a direction. Turn up the expression. Reveal the structure underneath. A small, living study in the decisions that make a design."/><section className="container"><DesignPlayground/></section><section className="container section playground-after"><h2>That’s one small experiment.<br/><em>Imagine what we could make together.</em></h2><Link className="button primary" href="/contact">Bring an idea <ArrowUpRight size={17}/></Link></section></main>;
  if(page==='privacy')return <main id="main-content"><PageIntro eyebrow="THE SMALL PRINT / PLAIN LANGUAGE" title="Your information," accent="treated thoughtfully." description="This page explains the information collected by this portfolio and how to get in touch about it."/><section className="container policy-body"><h2>When you get in touch</h2><p>Project enquiries, call requests, and reviews collect the details you choose to provide: your name, email, message, and relevant project or scheduling preferences. These are stored so Rushan can review and respond to them.</p><h2>Reviews</h2><p>A review is held for moderation. Your email is kept private. With your permission, your name, company, rating, and review may be published on this portfolio.</p><h2>Storage and site preferences</h2><p>Submissions are stored in the site’s database. Your project-layout preference is saved on your device. The site does not use advertising trackers. The hosting provider may process operational and security information needed to serve the site.</p><h2>Anonymous interaction counts</h2><p>The site counts project opens, contact and scheduling clicks, and form starts by page and day. No visitor identifier, message, email, or query string is sent with these events. Counts are retained for up to 90 days and respect Do Not Track and Global Privacy Control. Received submissions are counted separately in the private inbox.</p><h2>Review moderation</h2><p>Reviews are checked for consent and a genuine project relationship before publication. Spam, abusive content, and unverifiable claims may be rejected; critical feedback is not excluded merely for being negative. You may request correction or removal by email.</p><h2>Call requests</h2><p>A requested time is a preference, not a confirmed appointment. Confirmation is arranged separately by email.</p><h2>Questions or deletion requests</h2><p>Contact <a href={`mailto:${email}`}>{email}</a> to ask about your information or request deletion. Include enough detail to identify your submission.</p><p className="small-note">Updated September 2026.</p></section></main>;
  return <main id="main-content"><PageIntro eyebrow="ACCESSIBILITY / OPEN TO EVERYONE" title="An experience" accent="you can make your own." description="This site is designed to be navigable with a keyboard, comfortable on small screens, and usable with touch or pointer input."/><section className="container policy-body"><h2>A quieter experience</h2><p>Your system’s reduced-motion setting is respected. All content remains available.</p><h2>Navigation and reading</h2><p>Use the skip-to-content link, visible keyboard focus, descriptive form labels, and native browser zoom. Interactive studies can be operated with buttons and keyboard controls.</p><h2>Something getting in the way?</h2><p>Accessibility is an ongoing practice. If a part of this site is difficult to use, email <a href={`mailto:${email}`}>{email}</a> with the page and the issue you encountered.</p><div className="social-links">{socials.slice(0,2).map(s=><a href={s.url} key={s.name} target="_blank" rel="noopener noreferrer">{s.name}<ArrowUpRight size={15}/></a>)}</div></section></main>;
}
