import { CoverImage } from '@/components/cover-image';
import type { Metadata } from 'next';
import Link from '@/components/site-link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { getPublishedContent } from '@/lib/published-content';
import { ReadingTools } from '@/components/reading-tools';
import { pageMetadata, jsonLd, siteOrigin } from '@/lib/seo';
type Props={params:Promise<{slug:string}>};
export const dynamicParams=false;
export async function generateStaticParams(){const {writings}=await getPublishedContent();return writings.map(w=>({slug:w.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {writings}=await getPublishedContent();const {slug}=await params;const item=writings.find(w=>w.slug===slug);return pageMetadata('/writing/'+slug,item?.originalTitle||'Writing not found',item?.description||'Writing by Rushan Haque.');}
export default async function WritingDetail({params}:Props){const {writings}=await getPublishedContent();const {slug}=await params;const item=writings.find(w=>w.slug===slug);if(!item)notFound();const technical=slug==='feedback-loop-collapse';return <main id="main-content"><article className="article container"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'CreativeWork',name:item.originalTitle,description:item.description,url:siteOrigin+'/writing/'+slug,...(item.author?{author:{'@type':'Person',name:item.author,url:siteOrigin}}:{}),...(technical?{datePublished:'2026-03-14',sameAs:item.url}:{})})}}/><Link href="/writing" className="back-link"><ArrowLeft size={15}/>The notebook</Link><header><span className="eyebrow">{item.category} / {technical?'14 March 2026':item.year} / {item.status}</span><h1 data-reveal>{item.title}</h1><p className="article-deck">{item.description}</p>{item.author&&<div className="article-byline"><span className="review-avatar">RH</span><div>{item.author}<span>{item.originalTitle}</span></div></div>}</header><CoverImage src={item.image} title={item.originalTitle} blurred={item.imageBlurred} large/><ReadingTools text={item.paragraphs.join(' ')}/><nav className="article-toc" aria-label="On this page"><strong>On this page</strong><a href="#overview">Overview</a><a href="#source">{item.url?'Source & context':'Publication status'}</a></nav><div className="article-body"><h2 id="overview">{technical?'The question behind the note':'About the work'}</h2>{item.paragraphs.map(p=><p key={p}>{p}</p>)}{technical&&<details><summary>Publication context and limitations</summary><p>This page is an introduction, not the complete argument. The source is a technical note deposited on Zenodo, not a claim of peer review. Definitions, assumptions, and limitations should be assessed in the original document.</p></details>}{slug==='aabshar-e-khayaal'&&<p lang="ur" dir="rtl" style={{fontSize:'2rem'}}>آبشارِ خیال</p>}<aside className="source-note" id="source"><h2>{item.url?'Read in context':'Still taking shape'}</h2><span>{item.source}</span>{item.url?<a href={item.url} target="_blank" rel="noopener noreferrer" className="button primary">{technical?'Read the full technical note':slug==='to-the-moon-and-beyond'?'View the book':'Explore the original collection'}<ArrowUpRight size={17}/></a>:<Link href="/contact" className="text-link">Get in touch about this work <ArrowUpRight size={16}/></Link>}</aside><nav className="article-related" aria-label="Related reading">{writings.filter(w=>w.slug!==slug).slice(0,2).map(w=><Link className="text-link" key={w.slug} href={'/writing/'+w.slug}>{w.originalTitle}<ArrowUpRight size={16}/></Link>)}</nav></div></article></main>;}
