import { BookObject } from '@/components/book-cover';
import type { Metadata } from 'next';
import Link from '@/components/site-link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { getPublishedContent } from '@/lib/published-content';
import { pageMetadata, jsonLd, siteOrigin } from '@/lib/seo';
type Props={params:Promise<{slug:string}>};
export const dynamicParams=false;
export async function generateStaticParams(){const {writings}=await getPublishedContent();return writings.map(w=>({slug:w.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {writings}=await getPublishedContent();const {slug}=await params;const item=writings.find(w=>w.slug===slug);return pageMetadata('/writing/'+slug,item?.originalTitle||'Writing not found',item?.description||'Writing by Rushan Haque.');}
export default async function WritingDetail({params}:Props){const {writings}=await getPublishedContent();const {slug}=await params;const item=writings.find(w=>w.slug===slug);if(!item)notFound();const technical=slug==='feedback-loop-collapse';return <main id="main-content"><article className="article container"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'CreativeWork',name:item.originalTitle,description:item.description,url:siteOrigin+'/writing/'+slug,...(item.author?{author:{'@type':'Person',name:item.author,url:siteOrigin}}:{}),...(technical?{datePublished:'2026-03-14',sameAs:item.url}:{})})}}/><Link href="/writing" className="back-link"><ArrowLeft size={15}/>All writing</Link><header><span className="eyebrow">{item.category} / {technical?'14 March 2026':item.year} / {item.status}</span><h1 data-reveal>{item.title}</h1><p className="article-deck">{item.description}</p></header><BookObject book={item} size="large"/><div className="article-body"><h2>{technical?'The question':'About'}</h2>{item.paragraphs.map(p=><p key={p}>{p}</p>)}{technical&&<details><summary>About this note</summary><p>An introduction, not the full argument. The source is a technical note on Zenodo, not peer reviewed.</p></details>}{slug==='aabshar-e-khayaal'&&<p lang="ur" dir="rtl" style={{fontSize:'2rem'}}>آبشارِ خیال</p>}<aside className="source-note" id="source"><h2>{item.url?'Read it':'Coming soon'}</h2><span>{item.source}</span>{item.url?<a href={item.url} target="_blank" rel="noopener noreferrer" className="button primary">{technical?'Read the full technical note':'View the book'}<ArrowUpRight size={17}/></a>:<Link href="/contact" className="text-link">Get in touch <ArrowUpRight size={16}/></Link>}</aside></div></article></main>;}
