'use client';
import { useId, useState } from 'react';
import { ArrowUpRight, Plus } from 'lucide-react';
import Link from '@/components/site-link';
const notes=[
  {title:'Let the setting speak.',text:'The architecture fills the frame. Its repeated arches lead the eye towards the centre, giving the opening a clear focal point.',x:50,y:23},
  {title:'Contrast creates hierarchy.',text:'A wide-set serif headline sits over the image, with an italic second line. The change in rhythm gives the positioning statement emphasis.',x:78,y:47},
  {title:'One obvious next step.',text:'“View collections” sits beneath the headline. The visitor can move from the brand’s atmosphere to its products without hunting through navigation.',x:50,y:77},
];
export function DesignDecision(){const [open,setOpen]=useState(false);const [active,setActive]=useState(0);const id=useId();return <section className="decision-study container" aria-labelledby={`${id}-title`}><div className="decision-intro"><span className="eyebrow">A CLOSER LOOK / ERFOLG LIVING</span><h2 id={`${id}-title`}>There’s a reason<br/><em>it feels this way.</em></h2><p>Three details in the opening composition. Look at the finished page, then explore how its visual hierarchy works.</p><button className="button outline" aria-expanded={open} aria-controls={`${id}-notes`} onClick={()=>setOpen(!open)}>{open?'See the finished composition':'Why this works'}<Plus size={18} style={{transform:open?'rotate(45deg)':undefined}}/></button></div><div className={`decision-media ${open?'is-annotated':''}`}><img src="/images/erfolg.webp" width="1600" height="769" loading="lazy" alt="Erfolg Living homepage: architectural photography, a centred serif headline, and a View Collections action"/>{open&&notes.map((note,i)=><button className="annotation-pin" key={note.title} style={{left:`${note.x}%`,top:`${note.y}%`}} aria-label={`Detail ${i+1}: ${note.title}`} aria-pressed={active===i} onClick={()=>setActive(i)}>{i+1}</button>)}</div><div id={`${id}-notes`} hidden={!open} className="decision-notes"><div role="group" aria-label="Composition details">{notes.map((note,i)=><button key={note.title} onClick={()=>setActive(i)} aria-pressed={active===i}>{String(i+1).padStart(2,'0')} {note.title}</button>)}</div><div aria-live="polite"><h3>{notes[active].title}</h3><p>{notes[active].text}</p><span className="small-note">A visual analysis of the shown composition; no conversion uplift is claimed.</span></div></div><Link href="/projects/erfolg-living" className="text-link">Explore the project <ArrowUpRight size={18}/></Link></section>;}
