'use client';
import { useRef, useState, type PointerEvent } from 'react';
import Link from '@/components/site-link';
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, Copy, RotateCcw, SlidersHorizontal } from 'lucide-react';
import { gsap } from 'gsap';
import { useMotion } from '@/components/site-motion';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Slider } from '@/components/ui/slider';
import { email } from '@/lib/content';
import { useContent } from '@/components/content-provider';

export function Sculpture(){
  const ref=useRef<HTMLDivElement>(null); const [view,setView]=useState(false); const {reduced}=useMotion();
  function move(e:PointerEvent<HTMLDivElement>){if(reduced||e.pointerType==='touch')return;const box=e.currentTarget.getBoundingClientRect();gsap.to(ref.current,{rotateY:((e.clientX-box.left)/box.width-.5)*18,rotateX:-((e.clientY-box.top)/box.height-.5)*14,x:((e.clientX-box.left)/box.width-.5)*12,duration:.8,ease:'power2.out',overwrite:true});}
  return <div className={`hero-object ${view?'alternate-view':''}`} onPointerMove={move} onPointerLeave={()=>gsap.to(ref.current,{rotateY:0,rotateX:0,x:0,duration:1,overwrite:true})}><div ref={ref} className="sculpture-tilt"><img className="sculpture-image" src="/images/aperture.webp" width="1254" height="1254" alt="An open architectural sculpture in brushed silver and forest green" fetchPriority="high"/></div><span className="object-coordinate coordinate-a">FORM STUDY — 001</span><span className="object-coordinate coordinate-b">SILVER / FOREST</span><button className="object-control" onClick={()=>setView(!view)} aria-pressed={view}><RotateCcw size={13}/>{view?'Reset perspective':'Shift perspective'}</button><div className="object-note"><span className="note-line"/><span>AN OPEN MIND.<br/>AN OPEN FORM.</span></div></div>;
}

const presets=[{name:'Editorial',word:'Considered.',line:'A little space. A different perspective.',serif:true},{name:'Expressive',word:'What if?',line:'Good things begin with a better question.',serif:false},{name:'Quiet',word:'Less, but felt.',line:'Let the idea do the talking.',serif:true}];
export function DesignPlayground(){
  const [preset,setPreset]=useState(0);const [expression,setExpression]=useState([45]);const [grid,setGrid]=useState(false);const stage=useRef<HTMLDivElement>(null);const {reduced}=useMotion();
  function choose(i:number){setPreset(i);if(!reduced)gsap.fromTo(stage.current,{opacity:.35,y:14},{opacity:1,y:0,duration:.6,ease:'power3.out'});}
  return <div className="design-playground" data-reveal><div className="playground-controls"><div className="playground-label"><SlidersHorizontal size={17}/><span>YOU’RE THE ART DIRECTOR</span></div><div className="preset-options" role="group" aria-label="Art direction">{presets.map((p,i)=><button key={p.name} onClick={()=>choose(i)} aria-pressed={preset===i}>{p.name}<span>0{i+1}</span></button>)}</div><div className="expression-control"><label id="expression-label">Expression <span>{expression[0]}%</span></label><Slider aria-labelledby="expression-label" value={expression} onValueChange={setExpression} min={0} max={100} step={1}/><div className="range-labels"><span>Quiet</span><span>Unexpected</span></div></div><button className="grid-switch" aria-pressed={grid} onClick={()=>setGrid(!grid)}><span>{grid?<Check size={12}/>:null}</span>Reveal the structure</button><p>Different personalities.<br/>The same attention to detail.</p></div><div className={`playground-stage ${grid?'show-grid':''}`} style={{'--expression':expression[0]} as React.CSSProperties}><div className="stage-corners" aria-hidden="true"/><span className="stage-meta">STUDY 0{preset+1} / LIVE COMPOSITION</span><div ref={stage} className="stage-composition"><span className="stage-asterisk" aria-hidden="true">✳</span><h3 style={{fontFamily:presets[preset].serif?'var(--font-serif)':'var(--font-sans)',fontStyle:presets[preset].serif?'italic':'normal'}}>{presets[preset].word}</h3><p>{presets[preset].line}</p></div><span className="stage-caption">Nothing here is accidental.<span>Including the space.</span></span>{grid&&<span className="grid-annotation">12 columns · deliberate alignment</span>}</div></div>;
}
export function ServiceAccordion(){const {services}=useContent();return <Accordion type="single" collapsible defaultValue="0" className="service-accordion">{services.map((service,i)=><AccordionItem key={service.title} value={String(i)}><AccordionTrigger><span className="service-number">0{i+1}</span><span className="service-name">{service.title}<small>{service.subtitle}</small></span></AccordionTrigger><AccordionContent><div className="service-content"><p>{service.description}</p><ul>{service.items.map(item=><li key={item}>{item}</li>)}</ul><Link href={`/contact?service=${encodeURIComponent(service.title)}`} className="text-link">Let’s explore it <ArrowUpRight size={16}/></Link></div></AccordionContent></AccordionItem>)}</Accordion>;}
export function ReviewCarousel(){const {reviews}=useContent();const [index,setIndex]=useState(0);const content=useRef<HTMLDivElement>(null);const {reduced}=useMotion();if(!reviews.length)return <p>New perspectives are on their way.</p>;const current=index%reviews.length;function change(direction:number){setIndex((current+direction+reviews.length)%reviews.length);if(!reduced)gsap.fromTo(content.current,{opacity:0,y:12},{opacity:1,y:0,duration:.5});}return <div className="review-carousel"><div ref={content} aria-live="polite" aria-atomic="true"><blockquote>“{reviews[current].quote}”</blockquote><div className="review-person"><span className="review-avatar">{reviews[current].name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><div><strong>{reviews[current].name}</strong><span>{reviews[current].company}</span></div></div></div><div className="review-controls"><span>{String(current+1).padStart(2,'0')} <span>/ {String(reviews.length).padStart(2,'0')}</span></span><div><button aria-label="Previous review" onClick={()=>change(-1)}><ArrowLeft size={20}/></button><button aria-label="Next review" onClick={()=>change(1)}><ArrowRight size={20}/></button></div></div></div>;}
export function CopyEmail(){const [status,setStatus]=useState('');async function copy(){try{await navigator.clipboard.writeText(email);setStatus('Copied');}catch{setStatus('Use the email link');}window.setTimeout(()=>setStatus(''),3000);}return <button className="copy-email" onClick={copy} aria-label="Copy email address">{status?<Check size={16}/>:<Copy size={16}/>}<span aria-live="polite">{status||'Copy'}</span></button>;}
