'use client';
import { useEffect, useRef, useState } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { ArrowDown, ArrowUpRight, ArrowLeft, ArrowRight, Plus } from 'lucide-react';
import Link from '@/components/site-link';
import { useContent } from '@/components/content-provider';
import { useMotion } from '@/components/site-motion';
import { LiquidHover } from '@/components/liquid-hover';
import { ThoughtSculpture } from '@/components/thought-sculpture';
import { responsive } from '@/lib/images';
import dimensions from '@/generated/image-dimensions.json';
import profile from '@/content/profile.json';
import sourcePages from '@/content/source-pages.json';
gsap.registerPlugin(ScrollTrigger);
const imageSizes=dimensions as Record<string,{width:number;height:number}>;
const stories:Record<string,{line:string;note:string;field:string}>={
 'erfolg-living':{line:'A room. A rhythm. A feeling.',note:'Architectural lines and a quiet palette give an interiors collection space to speak.',field:'INTERIORS & LIVING'},
 taif:{line:'Objects with a point of view.',note:'An image-led commercial presence, built around the character of the collection.',field:'OBJECTS & INTERIORS'},
 aurelio:{line:'Make the first impression count.',note:'A distinct visual identity, carried from the opening frame through the website.',field:'BRAND & COMMERCE'},
 velora:{line:'A world still taking shape.',note:'An evolving commercial website. The design is here; the story is still being written.',field:'IN DEVELOPMENT'},
 'casa-and-crop':{line:'Rooted in the everyday.',note:'A commercial website shaped around its own collection, character, and visual language.',field:'LIFESTYLE & COMMERCE'},
};
export function PortfolioExperience(){
 const root=useRef<HTMLElement>(null);const {projects,writings,experience,education,services,reviews,certifications}=useContent();const {reduced}=useMotion();const [review,setReview]=useState(0);
 const works=projects.filter(p=>p.category==='Client work'&&p.image).slice(0,5);const currentReview=reviews[review];
 useEffect(()=>{if(!root.current||reduced)return;const ctx=gsap.context(()=>{
  gsap.from('.px-hero-title .px-line>span',{y:35,opacity:0,duration:1.15,stagger:.14,ease:'power4.out',clearProps:'transform,opacity'});
  gsap.utils.toArray<HTMLElement>('.px-appear').forEach(el=>gsap.from(el,{y:30,duration:1,ease:'power3.out',clearProps:'transform',scrollTrigger:{trigger:el,start:'top 94%',once:true}}));
  gsap.fromTo('.px-manifesto .px-word',{color:'#879182'},{color:'#f1f0e6',stagger:.08,ease:'none',scrollTrigger:{trigger:'.px-manifesto',start:'top 75%',end:'bottom 65%',scrub:.5}});
  gsap.utils.toArray<HTMLElement>('.px-case').forEach(el=>{const image=el.querySelector('.px-case-visual');gsap.fromTo(image,{y:45,scale:.975},{y:0,scale:1,ease:'none',scrollTrigger:{trigger:el,start:'top 95%',end:'center 65%',scrub:.7}});gsap.fromTo(el.querySelector('.px-case-rule'),{scaleX:0},{scaleX:1,ease:'none',scrollTrigger:{trigger:el,start:'top 85%',end:'bottom 75%',scrub:.5}});});
  gsap.utils.toArray<HTMLElement>('.px-publication').forEach((el,i)=>gsap.from(el,{rotation:i%2?3:-3,y:45,ease:'power2.out',duration:1.2,clearProps:'transform',scrollTrigger:{trigger:el,start:'top 92%',once:true}}));
  const about=root.current?.querySelector('.px-portrait');if(about)gsap.fromTo(about,{clipPath:'inset(8% 8% 8% 8%)'},{clipPath:'inset(0% 0% 0% 0%)',ease:'none',scrollTrigger:{trigger:about,start:'top 90%',end:'center 70%',scrub:.6}});
 },root);return()=>ctx.revert();},[reduced]);
 return <main id="main-content" className="portfolio-experience" ref={root}>
  <section className="px-hero" aria-labelledby="px-title">
   <div className="px-hero-meta"><span>RUSHAN HAQUE — INDEPENDENT PRACTICE</span><span>MORADABAD, INDIA · AVAILABLE WORLDWIDE</span></div>
   <div className="px-hero-composition"><h1 id="px-title" className="px-hero-title"><span className="px-line"><span>Logic.</span></span><span className="px-line"><span><em>& feeling.</em></span></span></h1><ThoughtSculpture/><div className="px-art-caption"><span>FIG. 01 — A CONTINUOUS THOUGHT</span><span>STRUCTURE ↔ INSTINCT</span></div></div>
   <div className="px-hero-bottom"><p>Developer by discipline.<br/>Writer by instinct.</p><p>I build things that work.<br/>And make them <em>feel like something.</em></p><a href="#selected-work" className="px-round-link"><span>Explore the work</span><ArrowDown size={24}/></a></div>
   <nav className="px-chapters" aria-label="Homepage chapters"><a href="#selected-work">01 / Selected works</a><a href="#writing">02 / The written world</a><a href="#services">03 / Beyond the build</a><a href="#journey">04 / The person</a></nav>
  </section>
  <section className="px-manifesto"><span className="px-label">A NOTE BEFORE THE WORK</span><h2>{'The best things happen where precision meets a little unpredictability.'.split(' ').map((w,i)=><span className="px-word" key={i}>{w} </span>)}</h2><div className="px-manifesto-foot"><span className="px-asterisk" aria-hidden="true">✳</span><p>A website should have a point of view.<br/>So should the person building it.</p><a href="#selected-work" aria-label="Continue to selected works"><ArrowDown size={30}/></a></div></section>
  <section id="selected-work" className="px-work" aria-labelledby="px-work-title"><header className="px-section-head px-appear"><span className="px-label">01 / SELECTED WORKS · 2025—2026</span><h2 id="px-work-title">Different worlds.<br/><em>One curious mind.</em></h2><p>Five websites. Five different starting points.<br/>Scroll through the work, one story at a time.</p></header>
   {works.map((work,i)=>{const story=stories[work.slug];const size=imageSizes[work.image!]??{width:1600,height:780};return <article className="px-case" key={work.slug} id={'case-'+work.slug}><div className="px-case-top"><span className="px-case-index">0{i+1}</span><h3><Link href={'/projects/'+work.slug}>{work.title}</Link></h3><span>{story?.field??work.discipline}<br/>{work.year} / {work.status}</span></div><div className="px-case-layout"><div className="px-case-aside"><h4>{story?.line??work.title}</h4><p>{story?.note??work.description}</p><Link href={'/projects/'+work.slug} className="px-text-link">Explore project <ArrowUpRight size={18}/></Link>{work.url&&<a href={work.url} target="_blank" rel="noopener noreferrer" className="px-site-link">Visit website ↗</a>}</div><Link className="px-case-visual" href={'/projects/'+work.slug} aria-label={`${work.title} — explore the project`}><LiquidHover><img src={work.image!} {...responsive(work.image,'(max-width: 760px) 92vw, 76vw')} width={size.width} height={size.height} alt={`${work.title} website, full preview`} loading="lazy" decoding="async"/></LiquidHover></Link></div><div className="px-case-bottom"><span>DESIGN & DEVELOPMENT</span><span>INDEPENDENT WORK / RUSHAN HAQUE</span></div><div className="px-case-rule"/></article>;})}
   <Link className="px-archive-link" href="/projects"><span>That was a chapter.<br/><em>There’s a whole archive.</em></span><span className="px-archive-number">{projects.length}<ArrowUpRight size={40}/></span></Link>
  </section>
  <section id="writing" className="px-writing"><header className="px-writing-head px-appear"><span className="px-label">02 / THE WRITTEN WORLD</span><h2>Not everything<br/>needs to <em>compile.</em></h2><div><span className="px-writing-mark" lang="ur" dir="rtl" aria-hidden="true">خیال</span><p>Research asks questions.<br/>Poetry makes room for them.<br/>Books follow the thought a little further.</p><Link href="/writing" className="px-text-link">Enter the reading room <ArrowUpRight size={18}/></Link></div></header>
   <div className="px-publications">{writings.map((item,i)=><Link className="px-publication" href={'/writing/'+item.slug} key={item.slug}><div className="px-publication-image">{item.image&&<img src={item.image} {...responsive(item.image,'(max-width: 760px) 85vw, 40vw')} alt={`${item.originalTitle} cover`} loading="lazy" decoding="async" className={item.imageBlurred?'px-unreleased':''}/>}<span className="px-publication-number">P/0{i+1}</span>{item.status==='Forthcoming'&&<span className="px-coming">FORTHCOMING</span>}</div><div className="px-publication-caption"><span>{item.category} / {item.year}</span><h3>{item.originalTitle}</h3><ArrowUpRight size={22}/></div></Link>)}</div>
  </section>
  <section id="services" className="px-practice"><div className="px-practice-title px-appear"><span className="px-label">03 / BEYOND THE BUILD</span><h2>A website is<br/>only the<br/><em>beginning.</em></h2><p>From the first sketch to the systems behind it. Design and development by me; specialist services delivered with trusted partners.</p><Link className="px-text-link" href="/services">Explore the services <ArrowUpRight size={18}/></Link><Link className="px-text-link" href="/areas-served">Based here. Working everywhere. <ArrowUpRight size={18}/></Link></div><div className="px-service-list">{services.map((service,i)=><details key={service.title}><summary><span>0{i+1}</span><h3>{service.title}</h3><Plus size={24}/></summary><div><p>{service.description}</p><ul>{service.items.map(item=><li key={item}>{item}</li>)}</ul><Link href="/contact" className="px-text-link">Talk about this <ArrowUpRight size={18}/></Link></div></details>)}<div className="px-service-index">{sourcePages.filter(p=>p.kind==='Service'&&p.slug!=='services').map(p=><Link href={'/'+p.slug} key={p.slug}>{p.title} ↗</Link>)}</div></div></section>
  <section id="journey" className="px-about"><header className="px-section-head"><span className="px-label">04 / THE PERSON BEHIND THE PIXELS</span><h2>Still learning.<br/><em>Always looking.</em></h2></header><div className="px-about-intro"><figure className="px-portrait"><img src={profile.portrait} alt="Rushan Haque" width="853" height="878" loading="lazy"/><figcaption>RUSHAN HAQUE / MORADABAD, INDIA</figcaption></figure><div className="px-about-note"><span className="px-label">A PRACTICE WITHOUT A SINGLE LANE</span><p>{profile.bio}</p><p className="px-about-hand">Different disciplines.<br/>The same restless curiosity.</p><div className="px-facts"><span><strong>{certifications.filter(c=>c.category==='Training'||c.category==='Job simulations').length}</strong>Learning milestones</span><span><strong>03</strong>Languages spoken</span><span><strong>{experience.length.toString().padStart(2,'0')}</strong>Roles & perspectives</span><span><strong>40+</strong>Projects contributed to</span></div><span className="px-language-note">ENGLISH · HINDI · URDU</span><Link href="/certifications" className="px-text-link">Credentials & original documents <ArrowUpRight size={18}/></Link></div></div><div className="px-timeline"><span className="px-label">THE THREAD SO FAR</span>{experience.map(item=><article key={item.role+item.company}><span>{item.period}</span><div><h3>{item.role}</h3><span>{item.company}</span></div><p>{item.description}</p></article>)}</div><div className="px-education">{education.map(item=><div key={item.title}><span className="px-label">EDUCATION / {item.detail}</span><h3>{item.title}</h3><p>{item.institution}</p></div>)}</div></section>
  <section id="reviews" className="px-voices"><div className="px-voices-heading"><span className="px-label">05 / THE OTHER SIDE OF THE CONVERSATION</span><h2>Good work.<br/><em>Real people.</em></h2><Link href="/reviews" className="px-text-link">Read all {reviews.length} reviews <ArrowUpRight size={18}/></Link></div>{currentReview&&<div className="px-review"><span className="px-quote-mark" aria-hidden="true">“</span><div aria-live="polite" aria-atomic="true"><blockquote key={review}>{currentReview.quote}</blockquote><div className="px-review-author"><strong>{currentReview.name}</strong><span>{currentReview.company}{currentReview.location?' / '+currentReview.location:''}</span></div></div><div className="px-review-controls"><span>{String(review+1).padStart(2,'0')} / {String(reviews.length).padStart(2,'0')}</span><button aria-label="Previous review" onClick={()=>setReview((review+reviews.length-1)%reviews.length)}><ArrowLeft size={22}/></button><button aria-label="Next review" onClick={()=>setReview((review+1)%reviews.length)}><ArrowRight size={22}/></button><Link href="/write-a-review">Add your words ↗</Link></div></div>}</section>
  <aside className="px-on-the-bench"><span className="px-label">POSTSCRIPT / PRODUCTS</span><p>Nothing shipped yet. <em>Two on the bench.</em></p><Link href="/products" className="px-text-link">See what’s taking shape <ArrowUpRight size={18}/></Link></aside>
 </main>;
}
