/* scripts/build-pages.mjs — generate the service and location pages.
 *
 * Every generated page is assembled from contact.html's own shell, so the
 * navigation, footer, stylesheets and scripts are byte-identical to the rest
 * of the site and can never drift out of sync with it. Only the <head> meta
 * and the <main> content are generated.
 *
 * The FAQ blocks are rendered here AND read by scripts/seo-schema.mjs from the
 * same data files, so the visible answers and the FAQPage markup are guaranteed
 * to match — Google only honours FAQ markup whose answers are on the page.
 *
 *   node scripts/build-pages.mjs           # write
 *   node scripts/build-pages.mjs --check   # verify committed pages are current
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { SERVICES } from '../data/seo-services.mjs';
import { LOCATIONS, locationFAQ } from '../data/seo-locations.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const SITE = 'https://www.rushanhaque.in';

/* ── html helpers ─────────────────────────────────────────────────────── */
const esc = (s) =>
  String(s == null ? '' : s)
    .replace(/&(?!(?:amp|lt|gt|quot|#39|mdash|ndash|nbsp|hellip);)/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

/* Content strings are authored with entities already in them (&amp;, &mdash;),
   so they pass through as written; only interpolated values get escaped. */
const raw = (s) => String(s == null ? '' : s);

/* ── shell ────────────────────────────────────────────────────────────── */
function shell() {
  const src = readFileSync(join(ROOT, 'contact.html'), 'utf8');
  const START = '<!-- Page Content Start -->';
  const END = '<!-- Page Content End -->';
  const i = src.indexOf(START);
  const j = src.indexOf(END);
  if (i < 0 || j < 0) throw new Error('build-pages: page content markers missing in contact.html');
  return { head: src.slice(0, i), tail: src.slice(j) };
}

function buildHead(head, { url, title, description }) {
  let h = head;
  const rep = (find, replace, label) => {
    if (!h.includes(find)) throw new Error(`build-pages: head anchor missing (${label})`);
    h = h.split(find).join(replace);
  };

  rep('<title>Hire a Web Developer in Moradabad | Rushan Haque</title>',
      `<title>${raw(title)}</title>`, 'title');
  rep('content="Start a website project with Rushan Haque — web developer and designer in Moradabad, India. Custom websites, ecommerce and web apps. Get a quote today."',
      `content="${raw(description)}"`, 'description');
  rep(`<link rel="canonical" href="${SITE}/contact">`,
      `<link rel="canonical" href="${url}">`, 'canonical');
  rep(`<meta property="og:url" content="${SITE}/contact">`,
      `<meta property="og:url" content="${url}">`, 'og:url');
  rep('content="Hire a Web Developer in Moradabad — Rushan Haque">',
      `content="${raw(title).replace(/ \| Rushan Haque$/, ' — Rushan Haque')}">`, 'og/tw title');
  rep('content="Start a website project — custom websites, ecommerce and web apps, built in Moradabad.">',
      `content="${raw(description)}">`, 'og/tw desc');

  /* schema is regenerated by scripts/seo-schema.mjs — leave only the markers */
  h = h.replace(
    /[ \t]*<!-- rh:schema[\s\S]*?<!-- \/rh:schema -->/,
    '    <!-- rh:schema — generated by scripts/seo-schema.mjs, do not edit by hand -->\n    <!-- /rh:schema -->'
  );
  return h;
}

/* ── page fragments ───────────────────────────────────────────────────── */
function headline({ eyebrow, mark, h1, answer, facts }) {
  return `      <!-- Section - Inner Headline Start -->
      <div class="mxd-section blur-section">
        <div class="mxd-container grid-l-container">
          <div class="mxd-block loading-wrap">
            <div class="inner-headline">
              <div class="container-fluid p-0">
                <div class="row g-0">
                  <div class="col-12 mxd-grid-item">
                    <div class="inner-headline__breadcrumbs loading-fade">
                      <div class="breadcrumbs__nav">
                        <span><a href="/"><span class="mxd-scramble">Home</span></a></span>
                        <span class="current-item">${raw(h1)}</span>
                      </div>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="inner-headline__content has-medium-title">
                      <div class="container-fluid p-0">
                        <div class="row g-0">
                          <div class="col-12 col-xl-7 mxd-grid-item">
                            <div class="a-index">
                              <span class="a-index__no">${raw(mark)}</span>
                              <span class="a-index__label">${raw(eyebrow)}</span>
                              <span class="a-index__rule"></span>
                            </div>
                            <div class="inner-headline__title">
                              <h1 class="medium loading-split">${raw(h1)}</h1>
                            </div>
                            <ul class="a-contact-facts">
${facts.map(([k, v]) => `                              <li>
                                <span class="a-meta">${raw(k)}</span>
                                <b>${raw(v)}</b>
                              </li>`).join('\n')}
                            </ul>
                          </div>
                          <div class="col-12 col-xl-5">
                            <div class="inner-headline__caption split-caption-title">
                              <div class="mxd-grid-item">
                                <!-- The direct answer, kept high on the page: this is the
                                     passage a search snippet or an AI assistant lifts. -->
                                <p class="t-bold t-large loading-split rh-local__answer">${raw(answer)}</p>
                                <div class="a-hero-actions">
                                  <a class="a-cta" href="/contact"><span>Start a project</span></a>
                                  <a class="a-cta a-cta--ghost" href="/work"><span>See the work</span></a>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Section - Inner Headline End -->
`;
}

function sectionOpen(no, label, h2, lede) {
  return `      <div class="mxd-section blur-section">
        <div class="mxd-container grid-l-container a-ruled">
          <div class="mxd-block">
            <div class="mxd-section-title pre-grid">
              <div class="container-fluid p-0">
                <div class="row g-0">
                  <div class="col-12 mxd-grid-item">
                    <div class="a-index">
                      <span class="a-index__no">${no}</span>
                      <span class="a-index__label">${raw(label)}</span>
                      <span class="a-index__rule"></span>
                    </div>
                    <h2 class="mxd-split-lines">${raw(h2)}</h2>
${lede ? `                    <p class="a-lede anim-uni-in-up">${raw(lede)}</p>` : ''}
                  </div>
                </div>
              </div>
            </div>
          </div>
`;
}

const sectionClose = `        </div>
      </div>
`;

function proseBlock(paras) {
  return `          <div class="mxd-block">
            <div class="container-fluid p-0">
              <div class="row g-0">
                <div class="col-12 mxd-grid-item">
                  <div class="rh-prose a-reveal">
${paras.map((p) => `                    <p>${raw(p)}</p>`).join('\n')}
                  </div>
                </div>
              </div>
            </div>
          </div>
`;
}

function bentoBlock(items) {
  return `          <div class="mxd-block">
            <div class="container-fluid p-0">
              <div class="row g-0">
                <div class="col-12 mxd-grid-item">
                  <div class="a-bento a-bento--even">
${items.map(([t, d], n) => `                    <div class="a-plate a-plate--live a-bento__cell a-reveal" data-reveal-delay="${n * 60}">
                      <div class="a-plate__in">
                        <div class="a-bento__body">
                          <div class="a-disc__head">
                            <h3 class="a-disc__title">${raw(t)}</h3>
                            <span class="a-meta">${String(n + 1).padStart(2, '0')}</span>
                          </div>
                          <p class="a-disc__descr">${raw(d)}</p>
                        </div>
                      </div>
                    </div>`).join('\n')}
                  </div>
                </div>
              </div>
            </div>
          </div>
`;
}

export function faqHTML(entries) {
  return entries.map(([q, a], i) => `                    <details class="a-faq__item a-reveal"${i === 0 ? ' open' : ''} data-reveal-delay="${i * 40}">
                      <summary class="a-faq__q">
                        <span class="a-faq__no">${String(i + 1).padStart(2, '0')}</span>
                        <span class="a-faq__label">${esc(q)}</span>
                        <span class="a-faq__mark" aria-hidden="true"></span>
                      </summary>
                      <div class="a-faq__a"><p>${esc(a)}</p></div>
                    </details>`).join('\n');
}

function faqSection(no, entries) {
  return sectionOpen(no, 'Questions', 'Questions people actually ask', '') +
`          <div class="mxd-block">
            <div class="container-fluid p-0">
              <div class="row g-0">
                <div class="col-12 mxd-grid-item">
                  <div class="a-faq">
${faqHTML(entries)}
                  </div>
                </div>
              </div>
            </div>
          </div>
` + sectionClose;
}

function relatedSection(no, links) {
  if (!links.length) return '';
  return sectionOpen(no, 'More', 'Related work', '') +
`          <div class="mxd-block">
            <div class="container-fluid p-0">
              <div class="row g-0">
                <div class="col-12 mxd-grid-item">
                  <ul class="rh-local__clients">
${links.map(([href, name, kind]) => `                    <li class="a-reveal">
                      <a href="${href}">
                        <b>${raw(name)}</b>
                        <span class="a-meta">${raw(kind)}</span>
                      </a>
                    </li>`).join('\n')}
                  </ul>
                </div>
              </div>
            </div>
          </div>
` + sectionClose;
}

function ctaSection(text) {
  return `      <div class="mxd-section blur-section padding-bottom-default">
        <div class="mxd-container grid-l-container">
          <div class="mxd-block">
            <div class="container-fluid p-0">
              <div class="row g-0">
                <div class="col-12 mxd-grid-item">
                  <div class="a-plate a-plate--ink a-reveal">
                    <div class="a-plate__in">
                      <div class="a-bento__body">
                        <div>
                          <span class="a-meta">Next step</span>
                          <p class="a-manifest">Got something worth building? <em>Tell me what it needs to do.</em></p>
                        </div>
                        <div class="a-bento__aside">
                          <p>${raw(text)}</p>
                          <a class="a-cta" href="/contact"><span>Start a project</span></a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
`;
}

/* ── assemble a service page ──────────────────────────────────────────── */
function servicePage(svc) {
  const byslug = Object.fromEntries(SERVICES.map((s) => [s.slug, s]));
  let n = 0;
  const no = () => String(++n).padStart(2, '0');

  let main = headline({
    eyebrow: svc.eyebrow,
    mark: 'S',
    h1: svc.h1,
    answer: svc.answer,
    facts: svc.facts,
  });

  for (const sec of svc.sections) {
    main += sectionOpen(no(), sec.h2.split(' ').slice(0, 2).join(' '), sec.h2, sec.lede || '');
    if (sec.prose) main += proseBlock(sec.prose);
    if (sec.items) main += bentoBlock(sec.items);
    main += sectionClose;
  }

  main += faqSection(no(), svc.faq);

  const rel = (svc.related || [])
    .filter((s) => byslug[s])
    .map((s) => [`/${s}`, byslug[s].h1, byslug[s].nav]);
  main += relatedSection(no(), rel);

  main += ctaSection('Send the brief &mdash; or the half-formed version of it &mdash; and you will get a quote with a timeline attached.');

  return main;
}

/* ── assemble a location page ─────────────────────────────────────────── */
function locationPage(loc) {
  let n = 0;
  const no = () => String(++n).padStart(2, '0');

  let main = headline({
    eyebrow: loc.city,
    mark: loc.city.slice(0, 1).toUpperCase(),
    h1: `Website designer in ${loc.city}`,
    answer: loc.answer,
    facts: [
      ['Based in', 'Moradabad, Uttar Pradesh'],
      ['Serving', `${loc.city}, ${loc.region}`],
      ['Distance', loc.distance.replace(/^about /, '')],
    ],
  });

  main += sectionOpen(no(), 'Local context', loc.industry.h2, loc.industry.lede);
  main += proseBlock(loc.industry.prose);
  main += sectionClose;

  /* City-specific, not the same six cards on every page.
     An identical services grid on ten city pages made each page roughly half
     the same document as every other one — which is the shape Google's spam
     policy calls a doorway network. These three items are written for this
     city's trade, and the shared service list below is a compact set of links
     instead of ten repetitions of the same six paragraphs. */
  /* "a Aligarh website" reads as a typo to exactly the reader you are trying
     to convince. Article choice follows the sound, not the spelling. */
  const article = /^[aeiou]/i.test(loc.city) ? 'an' : 'a';

  main += sectionOpen(no(), 'The brief',
    `What ${article} ${loc.city} website has to do`,
    `The general answer is the same everywhere. The specific one is not &mdash; and in ${loc.city} it usually comes down to these.`);
  main += bentoBlock(loc.needs);
  main += sectionClose;

  main += sectionOpen(no(), 'Services', 'Everything on offer',
    'Each of these is a service in its own right. Follow any one for what it involves.');
  main += `          <div class="mxd-block">
            <div class="container-fluid p-0">
              <div class="row g-0">
                <div class="col-12 mxd-grid-item">
                  <ul class="rh-local__areas rh-local__services">
${SERVICES.map((s) => `                    <li class="a-reveal"><a class="a-meta" href="/${s.slug}">${raw(s.nav)}</a></li>`).join('\n')}
                  </ul>
                </div>
              </div>
            </div>
          </div>
`;
  main += sectionClose;

  main += faqSection(no(), locationFAQ(loc));

  /* Cross-link to the four cities adjacent to this one in the list, wrapping
     at the ends. Taking a fixed slice instead would point every page at the
     same three cities, leaving the rest with a single inbound link from the
     hub — which is close enough to orphaned that Google treats them as low
     value. A rotating window gives every city roughly equal inbound links. */
  const i = LOCATIONS.findIndex((l) => l.slug === loc.slug);
  const neighbours = [1, 2, 3, 4]
    .map((k) => LOCATIONS[(i + k) % LOCATIONS.length])
    .filter((l) => l.slug !== loc.slug);

  const rel = [
    ['/website-designer-in-moradabad', 'Website designer in Moradabad', 'Base'],
    ...neighbours.map((l) => [`/${l.slug}`, `Website designer in ${l.city}`, l.region]),
    ['/areas-served', 'Every area served', 'All cities'],
  ];
  main += relatedSection(no(), rel);

  main += ctaSection(`Tell me what the site has to do for your ${loc.city} business, and you will get a quote with a timeline attached.`);

  return main;
}

/* ── hub pages ────────────────────────────────────────────────────────────
 * /services and /areas-served exist for two reasons. They are the breadcrumb
 * parents the generated pages point at, so those breadcrumbs resolve instead
 * of naming a 404. And they give the network a hub: eighteen pages linked only
 * from a footer are eighteen near-orphans, while eighteen pages linked from a
 * hub that is itself linked from the nav pass authority down properly. */
function servicesHub() {
  let n = 0;
  const no = () => String(++n).padStart(2, '0');

  let main = headline({
    eyebrow: 'Services',
    mark: 'S',
    h1: 'What I do',
    answer:
      'Websites, e-commerce, web applications, and the search and AI visibility work that decides whether any of it gets found. Everything is built from scratch by one person &mdash; the person you brief is the person who writes the code.',
    facts: [
      ['Disciplines', `${SERVICES.length} services`],
      ['Built by', 'One person, start to finish'],
      ['Serving', 'Moradabad, India &amp; remote'],
    ],
  });

  main += sectionOpen(no(), 'Services', 'Every service, in one place',
    'Each of these is a real discipline rather than a line on a price list. Follow any one for what it involves and what it costs you to skip.');
  main += `          <div class="mxd-block">
            <div class="container-fluid p-0">
              <div class="row g-0">
                <div class="col-12 mxd-grid-item">
                  <div class="a-bento a-bento--even">
${SERVICES.map((s, i) => `                    <a class="a-plate a-plate--live a-bento__cell a-reveal rh-plate-link" href="/${s.slug}" data-reveal-delay="${i * 60}">
                      <div class="a-plate__in">
                        <div class="a-bento__body">
                          <div class="a-disc__head">
                            <h3 class="a-disc__title">${raw(s.h1)}</h3>
                            <span class="a-meta">${String(i + 1).padStart(2, '0')}</span>
                          </div>
                          <p class="a-disc__descr">${raw(s.card)}</p>
                        </div>
                      </div>
                    </a>`).join('\n')}
                  </div>
                </div>
              </div>
            </div>
          </div>
`;
  main += sectionClose;
  main += ctaSection('Not sure which of these you need? Describe the problem and I will tell you &mdash; including when the answer is that you do not need me.');
  return main;
}

function areasHub() {
  let n = 0;
  const no = () => String(++n).padStart(2, '0');

  let main = headline({
    eyebrow: 'Areas served',
    mark: 'A',
    h1: 'Where the work goes',
    answer:
      'Based in Moradabad, Uttar Pradesh, working remotely everywhere else. Sites have shipped for businesses across northern India and for clients in Saudi Arabia, Poland and Nepal. A project has never needed both of us in the same room.',
    facts: [
      ['Based in', 'Moradabad, Uttar Pradesh'],
      ['Cities', `${LOCATIONS.length + 1} covered in detail`],
      ['Also', 'Remote, worldwide'],
    ],
  });

  main += sectionOpen(no(), 'Cities', 'Cities served across Uttar Pradesh and beyond',
    'Each of these has its own page, written around what that city actually makes and sells &mdash; because a brass exporter in Moradabad and a leather exporter in Kanpur do not have the same website problem.');
  main += `          <div class="mxd-block">
            <div class="container-fluid p-0">
              <div class="row g-0">
                <div class="col-12 mxd-grid-item">
                  <ul class="rh-local__clients">
                    <li class="a-reveal">
                      <a href="/website-designer-in-moradabad">
                        <b>Moradabad</b>
                        <span class="a-meta">Base &mdash; brass &amp; handicraft</span>
                      </a>
                    </li>
${LOCATIONS.map((l) => `                    <li class="a-reveal">
                      <a href="/${l.slug}">
                        <b>${raw(l.city)}</b>
                        <span class="a-meta">${raw(l.distance.replace(/^about /, ''))}</span>
                      </a>
                    </li>`).join('\n')}
                  </ul>
                </div>
              </div>
            </div>
          </div>
`;
  main += sectionClose;

  main += sectionOpen(no(), 'Remote', 'Everywhere else', '');
  main += proseBlock([
    'The city pages exist because local searches are how a lot of businesses look for a developer, and because the trade in each place genuinely changes the brief. They are not a limit.',
    'Work is remote-first. Briefs, feedback and handover happen over call and email, and that has been true for every project so far &mdash; including the ones for clients in Saudi Arabia, Poland and Nepal, none of whom have ever been in the same room as the person building their site.',
  ]);
  main += sectionClose;
  main += ctaSection('Wherever you are, the process is the same: send the brief and you will get a quote with a timeline attached.');
  return main;
}

/* ── run ──────────────────────────────────────────────────────────────── */
const { head, tail } = shell();
const stale = [];
let wrote = 0;
let same = 0;

const pages = [
  {
    file: 'services.html',
    url: `${SITE}/services`,
    title: 'Web Development & SEO Services in India | Rushan Haque',
    description:
      'Website design, e-commerce, web applications, SEO and GEO — every service in one place, built from scratch by one person in Moradabad, India.',
    main: servicesHub(),
  },
  {
    file: 'areas-served.html',
    url: `${SITE}/areas-served`,
    title: 'Areas Served Across Uttar Pradesh | Rushan Haque',
    description:
      'Website design and development across Moradabad, Rampur, Sambhal, Amroha, Bijnor, Meerut, Bareilly, Aligarh, Lucknow, Kanpur and Delhi NCR — and remote worldwide.',
    main: areasHub(),
  },
  ...SERVICES.map((s) => ({
    file: `${s.slug}.html`,
    url: `${SITE}/${s.slug}`,
    title: s.title,
    description: s.description,
    main: servicePage(s),
  })),
  ...LOCATIONS.map((l) => ({
    file: `${l.slug}.html`,
    url: `${SITE}/${l.slug}`,
    title: l.title,
    description: l.description,
    main: locationPage(l),
  })),
];

for (const p of pages) {
  const html =
    buildHead(head, p) +
    '<!-- Page Content Start -->\n' +
    '    <main id="mxd-page-content" class="mxd-page-content inner-page-content rh-local">\n\n' +
    p.main +
    '\n    </main>\n    ' +
    tail;

  const path = join(ROOT, p.file);
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;

  /* The committed file also carries the JSON-LD that scripts/seo-schema.mjs
     injects afterwards, which this script deliberately leaves empty. Compare
     with that block collapsed on both sides, or every page would look stale
     the moment the schema step ran and --check could never pass. */
  const withoutSchema = (s) =>
    s == null ? null : s.replace(/<!-- rh:schema[\s\S]*?<!-- \/rh:schema -->/, '<!--schema-->');

  if (withoutSchema(current) === withoutSchema(html)) { same++; continue; }
  if (CHECK) { stale.push(p.file); continue; }
  writeFileSync(path, html);
  wrote++;
}

if (CHECK && stale.length) {
  console.error(
    `\nGenerated pages are out of date (${stale.length}): ${stale.slice(0, 6).join(', ')}` +
    `${stale.length > 6 ? ', …' : ''}\nRun "npm run pages" and commit the result.`
  );
  process.exit(1);
}

console.log(
  CHECK
    ? `Generated pages are current (${pages.length}).`
    : `Pages OK — ${wrote} written, ${same} already current (${pages.length} total).`
);
